import streamlit as st
import pandas as pd
import plotly.express as px
import os
import config

# ==============================================================================
# 1. PAGE CONFIGURATION & SECURITY GATE
# ==============================================================================
st.set_page_config(page_title="Quantum Strategy Analytics Hub", layout="wide")

# Force strict HTTP verification layers directly within session allocations to lock out intruders
if "authenticated" not in st.session_state:
    st.session_state["authenticated"] = False

if not st.session_state["authenticated"]:
    st.title("🔐 Quantum Workspace Security Gate")
    user_input = st.text_input("Username Identification Profile:")
    pass_input = st.text_input("Secret Clearance Authentication Key:", type="password")
    
    if st.button("Transmit Matrix Handshake"):
        if user_input == config.DASHBOARD_USER and pass_input == config.DASHBOARD_PASS:
            st.session_state["authenticated"] = True
            st.rerun()
        else:
            st.error("Access Prohibited. Signature verification mismatch.")
            st.stop()

# ==============================================================================
# 2. AUTHORIZED ENVELOPE EXECUTION CONTENT
# ==============================================================================
st.title("🛡️ Quantum Strategy Workspace & Forward Sandbox Control")

# Caching the data load to prevent redundant disk reads on UI updates
@st.cache_data 
def fetch_telemetry(path):
    """
    Reads Parquet files generated by the XGBoost engine into Pandas DataFrames.
    Parquet format enables efficient columnar data storage and retrieval [1].
    """
    if os.path.exists(path):
        return pd.read_parquet(path, engine="pyarrow")
    return None

# Load the compiled results from your local drive
data = fetch_telemetry(config.RESULTS_FILE)
live_logs = fetch_telemetry(config.LIVE_LOG_FILE)
grid_logs = fetch_telemetry("grid_search_raw_logs.parquet")

# ==============================================================================
# 3. INTERACTIVE TABS
# ==============================================================================
tab1, tab2, tab3 = st.tabs(["🏆 Tournament Standings", "📡 Live Activity", "⚙️ System Health"])

with tab1:
    st.header("Model Leaderboard & Risk Profiles")
    
    if data is not None and not data.empty:
        # Sort leaderboard to locate the absolute system alpha leader
        sorted_data = data.sort_values(by="composite_score", ascending=False)
        alpha_leader = sorted_data.iloc
        
        # TOP KPI ROW
        st.subheader("Global Champion Model")
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Leading Sector", alpha_leader.get('sector', 'N/A'))
        c2.metric("Max Precision", f"{alpha_leader.get('precision', 0)*100:.2f}%")
        c3.metric("Optimum Features", int(alpha_leader.get('feat_count', 0)))
        c4.metric("Top Composite Score", round(alpha_leader.get('composite_score', 0), 2))
        
        # ADVANCED RISK METRICS TABLE
        st.subheader("Institutional Risk Metrics")
        st.caption("Tracking system stability using Sharpe, Sortino, Calmar, SQN, K-Ratio, and Omega scores.")
        
        # Filter for the advanced metrics we built into the engine
        risk_cols = ['sector', 'precision', 'composite_score', 'sharpe', 'sortino', 'calmar', 'sqn', 'k_ratio', 'omega']
        available_cols = [col for col in risk_cols if col in sorted_data.columns]
        st.dataframe(sorted_data[available_cols], use_container_width=True)
        
        # HYPERPARAMETER SENSITIVITY PLOT
        if grid_logs is not None and not grid_logs.empty:
            st.subheader("Hyperparameter Search Space Sensitivity")
            fig = px.scatter(
                grid_logs, 
                x="max_depth", 
                y="precision", 
                color="sector",
                size="best_iteration",
                title="Tree Depth vs Precision by Sector (XGBoost Grid Search)"
            )
            st.plotly_chart(fig, use_container_width=True)
            
    else:
        st.warning("Telemetry array empty. Kick off local engine grid calculations via main.py.")

with tab2:
    st.header("🕵️ Live Agent Activity & Veto Ledger")
    
    if live_logs is not None and not live_logs.empty:
        # Sort so the newest trades appear at the top
        live_logs = live_logs.sort_values(by="Timestamp", ascending=False)
        st.dataframe(live_logs, use_container_width=True)
        
        c1, c2 = st.columns(2)
        with c1:
            st.subheader("Execution vs. Veto Distribution")
            fig_status = px.pie(live_logs, names='Status', hole=0.4, title="Trade Action Ratios")
            st.plotly_chart(fig_status, use_container_width=True)
            
        with c2:
            st.subheader("Primary Veto Reasons")
            veto_data = live_logs[live_logs['Status'] != 'EXECUTED (PAPER)']
            if not veto_data.empty:
                fig_vetos = px.histogram(veto_data, y='Veto_Reason', orientation='h', title="Risk Manager Block Reasons")
                st.plotly_chart(fig_vetos, use_container_width=True)
            else:
                st.success("No trades have been vetoed yet.")
    else:
        st.info("Waiting for live data streaming. Ensure live_trader.py is running its scheduled loops.")

with tab3:
    st.header("RTX 4070 Ti Resource Monitor")
    st.write("GPU Status: **ACTIVE**")
    st.write(f"Operational Mode: **{config.RUN_MODE}**")
    st.write(f"Last UI Data Sync: {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')}")
    st.caption("Note: XGBoost automatically frees CUDA memory when the dataset bindings are unlinked during training, ensuring stability for long executions [2].")